apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: github-webhook-default
spec:
  destination:
    name: github-webhook
  precedence: 2
  route:
    - labels:
        version: v1
      weight: 100
