apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: istio-system
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
    - host: grafana.hightowerlabs.com 
      http:
        paths:
          - backend:
              serviceName: grafana
              servicePort: 3000
